name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ release  ]
permissions: write-all
jobs:
  build:
    name: Run renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        env:
          RENOVATE_REPOSITORIES: api3dao/logos
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_BASE_BRANCHES: develop
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}