name: Trigger on Registry Package Publish

on:
  repository_dispatch:
    types: [ release  ]
permissions:
    contents: write
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        repository: api3dao/logos
        event-type: release